config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'static_pages#home'

  get "welcome_user", to: "static_pages#welcome_user"
  get "faq", to: "static_pages#faq"

  resources 'users' do
    resources 'profile_pictures', only: [:create, :destroy]
  end

  resources 'properties' do
    get 'share', to: "properties#share" 
    get 'candidate_details', to: 'properties#show_candidate_details', as: 'candidate_details'
    delete 'delete-visits', to: "properties#destroy_all_slots" 
    resources 'property_pictures', only: [:create, :destroy]
    resources 'slots' do
      get 'candidate_details', to: 'slots#show_candidate_details', as: 'candidate_details'
    end
    member do
      #new candidate process
      get 'go-visit', to: "new_candidates#welcome_candidate"
      get 'step-1', to: "new_candidates#step1_login"
      get 'step1', to: "new_candidates#step1_logout"
      get 'step-2', to: "new_candidates#step2"
      get 'step-3', to: "new_candidates#step3"
    end
  end

  resources 'appointments', only: [:create, :show, :destroy] do
    resources 'candidate_slots', only: [:update, :destroy]
    resources 'candidate_messages', only: [:edit, :update, :destroy]
    resources 'candidate_documents', only: [:create, :destroy]
    resources 'candidate_dossierfacile_folders', only: [:create, :destroy]
    resources 'candidate_dossierfacile_links', only: [:create, :destroy]
    resources 'candidate_decisions', only: [:update]
    resources 'owner_decisions', only: [:update]
  end

  # scope '/checkout' do
  #   resources 'checkout', only: [:create]
  #   get 'success', to: 'checkout#success', as: 'checkout_success'
  #   get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
  # end

  namespace :admin do
    root 'welcome#index'
  end

end

app/models/slot.rb
class Slot < ApplicationRecord
  #Callbacks
  
  #Associations
  belongs_to :property
  has_many :appointments
  has_many :candidates, through: :appointments
  
  #Validations
  validate :start_date_cannot_be_in_the_past
  validate :overlaps_with_other?

  validates :start_date, presence: true
  validates :duration, presence: true
  validates :max_appointments, presence: true, numericality: { only_integer: true }

  def end_date
    start_date + duration.minutes
  end

  def period
    start_date..(end_date-1)
  end

  def duration? #converts seconds into minutes
    (end_date - start_date).to_i/(60)
  end

  def availability
    return (self.max_appointments - self.appointments.size)
  end
  
  def available?
    if self.availability > 0
      return true
    else
      return false
    end
  end

  def is_past?
    self.start_date < DateTime.now
  end

  private

  def start_date_cannot_be_in_the_past
    if start_date.present? && start_date < DateTime.now
      errors.add(:start_date, "Impossible de créer ou modifier un créneau de visite dans le passé.")
    end
  end

  def start_must_be_before_end_date
    errors.add(:start_date, "La date de fin doit être postérieure à la date de début") unless start_date < end_date
  end

  def overlaps_with_other?
    if (self.property)
      other_slots = self.property.slots
      is_overlapping = other_slots.any? do |other_slot|
        if other_slot != self
        period.overlaps?(other_slot.period)
        end
      end
      errors.add(:overlaps_with_other?, "Un créneau de visite existe déjà sur cette période") if is_overlapping
    end
  end

  # def add_to_calendar 
  #   # Create a calendar with an event
  #   cal = Icalendar::Calendar.new
  #   cal.event do |e|
  #     e.dtstart     = Icalendar::Values::DateTime.new(self.start_date)
  #     e.dtend       = Icalendar::Values::DateTime.new(self.end_date)
  #     e.summary     = "Visite du logement '#{self.property.title}' à #{self.property.city}"
  #   end
  #   cal.publish
  # end
  
end

app/controllers/slots_controller.rb
class SlotsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit]
  before_action :is_same_user_new, only: [:new]
  before_action :is_same_user_edit, only: [:edit]

  # for new property only

  def index
    @property = Property.find(params[:property_id]) # for Stripe
    @slots = Property.find(params[:property_id]).slots
  end

  # for both new property and existing property

  def new
    @redirect_path_value = redirect_path_new
    @slot = Slot.new
    @property = Property.find(params[:property_id])
    @minutes = Array.new(12).each_with_index.map { |n, i| (i + 1) * 15 }
    now = DateTime.now
    min = now.minute / 15 * 15 + 15
    @date = now.change(
      {
        hour: min >= 60 ? now.hour + 1 : now.hour,
        min: min % 60
      }
    )
  end
  
  def create
    redirect_path_value = redirect_path_create.values.first
    nb = nb_slots[:nb_slots].to_i
    one_is_success = false
    new_start_date = slot_params[:start_date].to_datetime
    duration = slot_params[:duration].to_i
    property = Property.find(params[:property_id])
    @property = Property.find(params[:property_id])
    @minutes = Array.new(12).each_with_index.map { |n, i| (i + 1) * 15 }
    slot = ""
    nb.times do |index|
      slot = Slot.new(slot_params)
      slot.property = property
      slot.start_date = new_start_date
      if slot.save then one_is_success = true end
      new_start_date = new_start_date + duration.minutes
    end
    if one_is_success
      flash[:success] = "Créneau(x) de visite ajouté(s) avec succès ✌️"
      if redirect_path_value == "new_property" #when new immolib property process
        redirect_to(property_slots_path(property))
      else #when in "mon espace immolib"
        redirect_to(property_path(property))
      end
    else
      flash[:warning] = slot.errors.full_messages
      if redirect_path_value == "new_property" #when new immolib property process
        redirect_to(new_property_slot_path(property, redirect_path: "new_property"))
      else #when in "mon espace immolib"
        redirect_to(new_property_slot_path(property, redirect_path: "existing_property"))
      end
    end
  end

  def destroy
    slot = Slot.find(params[:id])
    property = slot.property
    
    #update apts slot to nil
    property.appointments.each do |appointment|
      if appointment.slot_id != nil && !appointment.slot.is_past?
        appointment.update(slot_id: nil)
      end
    end

    #destroy slot
    slot.destroy

    if params[:new_property]
      flash[:success] = "Le créneau a bien été supprimé 👌"
      redirect_to property_slots_path(property)
    else
      flash[:success] = "Le créneau a bien été supprimé. Il ne sera plus accesible et les candidats inscrits sont automatiquement prévenus 👌"
      redirect_to(property_path(property))
    end
  end

  # for existing property only

  def show
    @slot = Slot.find(params[:id])
    @date_arr = ["", "janvier", "février", "mars", "avril", "mai", "juin", "juillet", "août", "septembre", "octobre", "novembre", "décembre"]
  end

  def show_candidate_details
    @appointment = Appointment.find(params[:appointment])
    respond_to do |format|
      format.js {}
    end
  end

  def edit
    @slot = Slot.find(params[:id])
    @date_arr = ["", "janvier", "février", "mars", "avril", "mai", "juin", "juillet", "août", "septembre", "octobre", "novembre", "décembre"]
    @property = @slot.property
    @minutes = Array.new(12).each_with_index.map { |n, i| (i + 1) * 15 }
    @date = @slot.start_date
  end

  def update
    @property = Property.find(params[:property_id])
    @slot = Slot.find(params[:id])
    @minutes = Array.new(12).each_with_index.map { |n, i| (i + 1) * 15 }
    @date = @slot.start_date
    @date_arr = ["", "janvier", "février", "mars", "avril", "mai", "juin", "juillet", "août", "septembre", "octobre", "novembre", "décembre"]

    if @slot.update(slot_params)
      flash[:success] = "Le créneau de visite a été edité avec succès. Les candidats inscrits sont automatiquement prévenus ✌️"
        redirect_to(property_path(@property))
    else
      flash.now[:warning] = @slot.errors.full_messages
      render :edit
    end
  end

  private

  def slot_params
    params.require(:slot).permit(
      :start_date,
      :duration,
      :max_appointments
    )
  end

  def nb_slots
    params.require(:slot).permit(
      :nb_slots
    )
  end

  def redirect_path_new
    params[:redirect_path]
  end

  def redirect_path_create
    params.require(:slot).permit(:redirect_path)
  end

  def is_same_user_new
    @user = Property.find(params[:property_id]).owner
    if @user == current_user
    elsif current_user.is_admin?
    else
      flash[:warning] = "Vous n'êtes pas autorisé à accéder à cette page ⛔"
      redirect_to root_path
    end
  end

  def is_same_user_edit
    @user = Slot.find(params[:id]).property.owner
    if @user == current_user
    elsif current_user.is_admin?
    else
      flash[:warning] = "Vous n'êtes pas autorisé à accéder à cette page ⛔"
      redirect_to root_path
    end
  end
end

app/helpers/slots_helper.rb
module SlotsHelper
end

app/views/slots/_candidate_list.html.erb
<div class="slot-wrapper__content__candidate c<%= a.candidate.id %> <%= first ? "active" : nil %>">
  <h3> 
    <%= a.candidate.first_name && a.candidate.last_name ? ("#{a.candidate.first_name} #{a.candidate.last_name}")  : a.candidate.email %> 
    <span class="slot-wrapper__content__candidate--subtitle"> - Fiche candidat </span>
  </h3>
</div>

app/views/slots/_created_property_slots.html.erb
<% slots.order("start_date ASC").each do |slot| %>
  <div class='slot-summary'>
    <p class="bolder"><%= slot.start_date.strftime(
      "Le %d/%m/%Y de %H:%M à #{slot.end_date.strftime('%H:%M')}"
      ) %></p>
    <p>Durée : <%= slot.duration %> minutes</p>
    <p>Nombre de candidats maximum : <%= slot.max_appointments %></p>
    <%= link_to "Supprimer ce créneau", property_slot_path(property_id: slot.property, id: slot, new_property: true), method: "delete" %>
  </div>
<% end %>

<%= link_to "Ajouter un créneau de visite", new_property_slot_path(property, redirect_path: "new_property"), class: "btn outline-btn-white bolder" %>

<%= link_to "Valider et passer à l'étape suivante", property_share_path(property), class: "btn big-btn white-btn bg-primary bolder" %>


app/views/slots/_show_candidate_details.html.erb
<div class="candidate-profile-details-wrapper">
  <div class="candidate-profile-details-section">
    <% if appointment.candidate.profile_picture.attached?%>
      <div class="profile-wrapper__informations__right mb1">
        <%= image_tag appointment.candidate.profile_picture, alt: 'profile picture' %>
      </div>
    <% else %>
      <div class="profile-wrapper__informations__right nopic mb1">
        <p> Aucune photo de profil </p>
      </div>
    <% end %>
    <% if appointment.candidate.first_name && appointment.candidate.last_name %>
      <h3> <%= appointment.candidate.first_name %> <%= appointment.candidate.last_name %> </h3>
    <% end %>
  </div>

  <div class="candidate-profile-details-section">
    <p class="bolder"><i class="fas fa-at"></i> Email</p>
    <p><%= appointment.candidate.email %></p>
  </div>

  <div class="candidate-profile-details-section">
    <p class="bolder"><i class="fas fa-phone-square-alt"></i> Tél</p>
    <%if appointment.candidate.phone_number %>
      <p><%= appointment.candidate.phone_number %></p>
    <% else %>
      <p><small><em>Non renseigné</em></small></p>
    <% end %>
  </div>

  <div class="candidate-profile-details-section">
    <p class="bolder"><i class="far fa-comment"></i> Message</p>
    <% if appointment.candidate_message && appointment.candidate_message != "" %>
      <p><em><%= simple_format(appointment.candidate_message) %></em></p>
    <% else %>
      <p><small><em>Aucun message</em></small></p>
    <% end %>
  </div>

  <% if appointment.property.owner_project == "rent" %>
    <div class="candidate-profile-details-section">

      <% if appointment.candidate_dossierfacile_folder.attached? %>
        <p class="bolder"><i class="far fa-folder-open"></i> Dossier de location (réalisé via <%= link_to "DossierFacile", "https://www.dossierfacile.fr/", class:"primary", target: '_blank' %>)</p>
        <p class="mb1"><small><em>DossierFacile est une plateforme publique gratuite d'aide à la création de dossier de location 100% conforme à la loi. <br/>Elle joue le rôle de tiers de confiance entre locataires et propriétaires.</em></small></p>
        <div class="candidate-document mb1">
          <p><span class="text-muted">Dossier&nbsp;:</span>
            <%= appointment.candidate_dossierfacile_folder.filename %> 
            <%# if doc.previewable? %>
              <%= link_to raw("<i class='far fa-eye'></i>"), rails_blob_path(appointment.candidate_dossierfacile_folder, disposition: 'preview', target: '_blank') %>
            <%# end %> 
            <%= link_to raw("<i class='fas fa-download'></i>"), rails_blob_path(appointment.candidate_dossierfacile_folder, disposition: 'attachment') %>
          </p>
          <% if appointment.candidate_dossierfacile_link && appointment.candidate_dossierfacile_link != "" %>
            <p><span class="text-muted">Lien du dossier&nbsp;:</span> <%= link_to appointment.candidate_dossierfacile_link, appointment.candidate_dossierfacile_link, target: '_blank' %></p>
          <% end %>
        </div>
        <p class="green"><small> ✔️ Dossier complet</small></p>

      <% elsif appointment.candidate_dossierfacile_link && appointment.candidate_dossierfacile_link != "" %>
        <p class="bolder"><i class="far fa-folder-open"></i> Dossier de location (réalisé via <%= link_to "DossierFacile", "https://www.dossierfacile.fr/", class:"primary", target: '_blank' %>)</p>
        <p class="mb1"><small><em>DossierFacile est une plateforme publique gratuite d'aide à la création de dossier de location 100% conforme à la loi. <br/>Elle joue le rôle de tiers de confiance entre locataires et propriétaires.</em></small></p>
        <p class="mb1"><span class="text-muted">Lien du dossier&nbsp;:</span> <%= link_to appointment.candidate_dossierfacile_link,appointment.candidate_dossierfacile_link, target: '_blank' %></p>
        <p class="green"><small> ✔️ Dossier complet</small></p>

      <% elsif appointment.candidate_documents.attached? %>
        <p class="bolder mb1"><i class="far fa-folder-open"></i> Dossier de location</p>
        <div class="mb1">
          <p class="text-muted">Liste des documents demandés pour un dossier 100% conforme à la loi&nbsp;:</p>
          <p><i class="fas fa-caret-right"></i> 1 pièce d'identité recto-verso</p>
          <p><i class="fas fa-caret-right"></i> 1 justificatif de domicile</p>
          <p><i class="fas fa-caret-right"></i> 1 justificatif de situation professionnelle</p>
          <p><i class="fas fa-caret-right"></i> 1 justificatif de ressources</p>
          <p><i class="fas fa-caret-right"></i> Dernier avis d’imposition</p>
        </div>
        <p class="text-muted">Documents transmis&nbsp;:</p>
        <% appointment.candidate_documents.each do |doc| %>
          <div class="candidate-document">
            <p>
              <%= doc.filename %> 
              <%# if doc.previewable? %>
                <%= link_to raw("<i class='far fa-eye'></i>"), rails_blob_path(doc, disposition: 'preview'), target: '_blank' %>
              <%# end %> 
              <%= link_to raw("<i class='fas fa-download'></i>"), rails_blob_path(doc, disposition: 'attachment') %>
            </p>
          </div>
        <% end %>
        <p><progress id="file" max="5" value="<%=appointment.candidate_documents.size%>" class="<%=appointment.candidate_documents.size > 4 ? 'full' : nil %>"> </progress></p>
        <% if appointment.candidate_documents.size < 5 %>
          <p><small><em>⚠️ Dossier incomplet. Nombre de document(s) transmis : <%= appointment.candidate_documents.size %> / 5</em></small></p>
        <% else %>
          <p class="green"><small> ✔️ Dossier complet</small></p>
        <% end %>
      
      <% else %>
        <p class="bolder mb1"><i class="far fa-folder-open"></i> Dossier de location</p>
        <div class="mb1">
          <p class="text-muted">Liste des documents demandés pour un dossier 100% conforme à la loi&nbsp;:</p>
          <p><i class="fas fa-caret-right"></i> 1 pièce d'identité recto-verso</p>
          <p><i class="fas fa-caret-right"></i> 1 justificatif de domicile</p>
          <p><i class="fas fa-caret-right"></i> 1 justificatif de situation professionnelle</p>
          <p><i class="fas fa-caret-right"></i> 1 justificatif de ressources</p>
          <p><i class="fas fa-caret-right"></i> Dernier avis d’imposition</p>
        </div>
        <small><p><em>⚠️ Ce candidat n'a pas encore transmis de documents</em></p></small>
      <% end %>
    </div>
  <% end %>

  <div class="form-page">
    <div class="form-page__form">
      <div class="candidate-profile-details-section text-center">
        <p><i class="fas fa-info"></i> <span class="bolder">Après la visite, le candidat pourra confirmer ou non son intérêt pour votre logement</span></p>
        <hr class="hr-black mw80 mb2 mt2">
        <%if appointment.property.owner_project == "rent"%>
          <p> Cette candidature ne vous convient pas ? Le dossier est incomplet ? Vous avez déjà validé une autre candidature ?</p>
        <%else%>
          <p> Cette candidature ne vous convient pas ? Vous avez déjà validé une offre d'achat ?</p>
        <%end%>
        <%= form_with model: appointment, url: appointment_owner_decision_path(appointment_id: appointment, id: appointment), method: "patch", local: true, class: "form", id: "item-form", multipart: true do |f| %>
          <%= f.hidden_field(:is_accepted, value:"false") %>
          <%= f.submit "Refuser la candidature", data: {confirm: "Êtes-vous sûr ?"}, class:"btn small-btn white-btn bg-warning" %>
        <%end%>
        <p><small><em><i class="fas fa-info-circle"></i> Le candidat sera automatiquement prévenu de votre décision et de l'annulation sa visite</em></small></p>
      </div>
    </div>
  </div>

</div>

app/views/slots/book_candidate.html.erb
<div class="slot-candidate-wrapper">
  <div class="slot-candidate-wrapper__title pt1 section-title">
    <h1>Étape 1/2 : sélection d'un créneau disponible</h1>
    <h2>Sélectionnez un créneau de visite parmi les propositions disponibles</h2>
    <p>Vous pourrez le modifier à tout moment depuis votre espace immolib</p>
  </div>
  <div class="container text-center">
    <div class="slot-candidate-wrapper__calendar mt2">
      <div id='calendar-wrapper'>
        <%= render partial:"appointments/candidate_calendar", locals: {property: @property, slots: @slots, date_arr: @date_arr} %>
      </div>

      <% if !current_user %>
        <div class="slot-candidate-wrapper__calendar__title text-center"> 
          <p> Inscrivez-vous pour sélectionner un créneau. </p>
          <%= link_to "M'inscrire", new_user_registration_path, class:"btn white-btn bg-primary" %>
        </div>
      <% end %>

      <% if current_user && @property.candidates.include?(current_user) %>
        <div class="center-btn">
          <%= link_to "Valider et passer à l'étape suivante", send_message_property_path(@property), class: "btn white-btn bg-primary center-btn" %>
        </div>
      <% else %>
        <div class="center-btn">
          <%= link_to "Merci de sélectionner un créneau", send_message_property_path(@property), class: "btn disabled center-btn"%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/slots/book_candidate.js.erb
document
  .getElementById('calendar-wrapper')
  .innerHTML = "<%= j render partial:'appointments/candidate_calendar', locals: {property: @property, slots: @slots, date_arr: @date_arr} %>";

app/views/slots/edit.html.erb
<%= link_to raw("<i class='fas fa-chevron-left'></i> Retour"), property_slot_path(@property, @slot), class: "return-link pt1 pl4" %>
<div class="container">
  <div class="form-page">
    <div class="form-page__form">
      <h3>Editez ce créneau de visite</h3>
      <br/>
      <div class='form-group'>
        <%= text_field_tag :start_date, '', id:'pickadate', class: 'form-control' %> 
      </div>
      <%= form_with model: @slot, url: [@property, @slot], local: true, class: "form", id: "item-form" do |f| %>
        <%= f.hidden_field :start_date, value: @date, id: 'start_date' %>
        <br/>
        <div class="form-group">
          <%= f.label "Durée (en minutes) *", class: "form-label" %>
          <%= f.select :duration, @minutes.collect { |m| [m, m] }, { include_blank: false } %>
        </div>
        <br/>
        <div class="form-group">
          <%= f.label "Nombre de visiteurs maximum *", class: "form-label" %>
          <p><small><i class="fas fa-info-circle"></i> La disponibilité du créneau est automatiquement mise à jour après chaque prise de RDV</small></p>
          <%= f.number_field :max_appointments, placeholder: "Indiquez un nombre maximum de visiteurs pour ce créneau", min: 1, max: 50, required: true %>
        </div>
        <br/>
        <%= f.hidden_field :redirect_path, :value => true %>
        <div class="form-group text-center"> 
          <%= f.submit "Editer le créneau", class: "btn white-btn bg-primary" %>
          <%= link_to 'Supprimer', property_slot_path(@slot), method: :delete, data: { confirm: "Etes-vous sûr de supprimer ce créneau ?" }, class: "delete" %>
        </div>
      <%end%>
      <p class="text-center mt2"><small><em><i class="fas fa-info-circle"></i> En cas de modification ou d'annulation, les candidats inscrits à ce créneau seront automatiquement prévenus par email</em></small></p>
    </div>
  </div>
</div>

<%= javascript_include_tag 'datepicker' %>

app/views/slots/index.html.erb
<div class="container">
  <div class="slot-candidate-wrapper__title section-title">
    <h1>Etape 2/3 : sélectionnez les créneaux de visite qui seront proposés aux candidats</h1>
    <p class="mt2">Vous pourrez les modifier à tout moment dans votre espace immolib</p>
  </div>
</div>
<div class="new-slot-wrapper pl4 pr4 pb4">
  <div class="new-slot-wrapper__content text-center">
    <% if @slots.count > 0 %>
      <%= render( partial: 'created_property_slots', locals: { slots: @slots, property: @property } ) %>
    <% else %>
      <%= link_to "Ajouter un créneau de visite", new_property_slot_path(@property, redirect_path: "new_property"), class: "btn big-btn outline-btn-white bolder" %>
    <% end %>
  </div>
</div>

app/views/slots/index_candidate.html.erb
<div class="slot-candidate-wrapper">
  <div class="slot-candidate-wrapper__title pt1">
    <h1>Etape 1/3 : sélection d'un créneau disponible</h1>
    <h2>Sélectionnez un créneau de visite parmi les propositions disponibles.</h2>
    <p>Les créneaux disponibles sont mis à jour automatiquement. 
      Si aucun d’eux ne vous convient, des créneaux peuvent se libérer en cas de modification ou annulation de candidats.
    </p>
  </div>
  <div class="slot-candidate-wrapper__calendar mt2">
    <%= render "candidate_calendar", property: @property %>

    <% if !current_user %>
      <div class="slot-candidate-wrapper__calendar__title text-center"> 
        <p> Inscrivez-vous pour sélectionner un créneau. </p>
        <%= link_to "M'inscrire", new_user_registration_path, class:"btn white-btn bg-primary" %>
      </div>
    <% end %>

  </div>
</div>

app/views/slots/new.html.erb
<% if @redirect_path_value == "new_property" %>
  <%= link_to raw("<i class='fas fa-chevron-left'></i> Retour"), property_slots_path(@property), class: "return-link pt1 pl4" %>
<% else %>
  <%= link_to raw("<i class='fas fa-chevron-left'></i> Retour"), property_path(@property), class: "return-link pt1 pl4" %>
<% end %>
<div class="container">
  <div class="form-page">
    <div class="form-page__form">
      <h2>Ajouter un créneau de visite</h2>
      <div class='form-group'>
        <input type='text' id='pickadate', class='form-control'>
      </div>
      <%= form_with model: @slot, url: [@property, @slot], local: true, class: "form", id: "item-form" do |f| %>
        <%= f.hidden_field :start_date, value: @date, id: 'start_date' %>
        <br/>
        <div class="form-group">
          <%= f.label "Durée du créneau (en minutes) *", class: "form-label bolder" %>
          <%= f.select :duration, @minutes.collect { |m| [m, m] }, { include_blank: false } %>
        </div>
        <br/>
        <div class="form-group">
          <%= f.label "Nombre de candidats maximum *", class: "form-label bolder" %>
          <p><small><i class="fas fa-info-circle"></i> La disponibilité du créneau est automatiquement mise à jour après chaque prise de RDV</small></p>
          <%= f.number_field :max_appointments, value: 1, min: 1, max: 50, required: true %>
        </div>
        <br/>
        <div class="form-group">
          <%= f.label "Nombre de répétitions successives du créneau", class: "form-label bolder" %>
          <p><small><i class="fas fa-info-circle"></i> Laissez à "1" si vous ne souhaitez pas répéter ce créneau</small></p>
          <%= f.number_field :nb_slots, value: 1, min: 1, max: 20, required: true %>
        </div>
        
        <% if @redirect_path_value == "new_property" %>
          <%= f.hidden_field :redirect_path, :value => "new_property" %>
          <% else %>
          <%= f.hidden_field :redirect_path, :value => "existing_property" %>
        <% end %>
        
        <br/>
        <div class="form-group"> 
          <%= f.submit "Valider", class: "btn white-btn bg-primary"%>
        </div>
      <%end%>
    </div>
  </div>
</div>

<%= javascript_include_tag 'datepicker' %>

app/views/slots/show.html.erb
<div class="slot-wrapper">
  <div class="slot-wrapper-left">
    <%= link_to raw("<i class='fas fa-chevron-left'></i> Retour"), property_path(params[:property_id]), class: "return-link" %>
    <div class="slot-wrapper__title">
      <h1 class="primary mb1">Mes candidats</h1>
      <p class="bolder"> Créneau du <%= @slot.start_date.strftime("%d") %> <%= @date_arr[@slot.start_date.strftime("%m").to_i] %> <%= @slot.start_date.strftime("%Y") %></p>
      <p class="bolder"> <%= @slot.start_date.strftime("%H:%M") %> - <%= @slot.end_date.strftime("%H:%M") %></p>
      <%if @slot.start_date > DateTime.now%>
        <%= link_to 'Editer le créneau', edit_property_slot_path(@slot), class:"btn white-btn bg-primary small-btn" %>
      <%end%>
    </div>
    <div class="slot-wrapper__content">
      <% if @slot.appointments.size > 0 %>
        <% firstSlot = true %>
        <% @slot.appointments.order("created_at DESC").each do |a| %>
          <%= link_to render(partial: "candidate_list", locals: {a: a, first: firstSlot}), property_slot_candidate_details_path(@slot.property, @slot, appointment: a), remote: true %>
          <% firstSlot = false %>
        <% end %>
      <% else %>
        <p><em> Aucun candidat inscrit sur ce créneau </em></p>
      <% end %>
    </div>
  </div>

  <div class="slot-wrapper-right">
    <%# Ajax for candidate profile details%>
    <% if @slot.appointments.size > 0 %>
      <%= render "show_candidate_details", appointment: @slot.appointments.first %>
    <% end %>
  </div>
</div>