config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'static_pages#home'

  get "welcome_user", to: "static_pages#welcome_user"
  get "faq", to: "static_pages#faq"

  resources 'users' do
    resources 'profile_pictures', only: [:create, :destroy]
  end

  resources 'properties' do
    get 'share', to: "properties#share" 
    get 'candidate_details', to: 'properties#show_candidate_details', as: 'candidate_details'
    delete 'delete-visits', to: "properties#destroy_all_slots" 
    resources 'property_pictures', only: [:create, :destroy]
    resources 'slots' do
      get 'candidate_details', to: 'slots#show_candidate_details', as: 'candidate_details'
    end
    member do
      #new candidate process
      get 'go-visit', to: "new_candidates#welcome_candidate"
      get 'step-1', to: "new_candidates#step1_login"
      get 'step1', to: "new_candidates#step1_logout"
      get 'step-2', to: "new_candidates#step2"
      get 'step-3', to: "new_candidates#step3"
    end
  end

  resources 'appointments', only: [:create, :show, :destroy] do
    resources 'candidate_slots', only: [:update, :destroy]
    resources 'candidate_messages', only: [:edit, :update, :destroy]
    resources 'candidate_documents', only: [:create, :destroy]
    resources 'candidate_dossierfacile_folders', only: [:create, :destroy]
    resources 'candidate_dossierfacile_links', only: [:create, :destroy]
    resources 'candidate_decisions', only: [:update]
    resources 'owner_decisions', only: [:update]
  end

  # scope '/checkout' do
  #   resources 'checkout', only: [:create]
  #   get 'success', to: 'checkout#success', as: 'checkout_success'
  #   get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
  # end

  namespace :admin do
    root 'welcome#index'
  end

end

app/models/user.rb
class User < ApplicationRecord
  #Callbacks
  after_create :welcome_send
  after_commit :add_default_picture, on: [:create, :update]

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:google_oauth2]

  #Associations
  has_many :properties, foreign_key: 'owner_id', dependent: :destroy
  has_many :appointments, foreign_key: 'candidate_id', dependent: :destroy
  has_one_attached :profile_picture, dependent: :destroy

  #Validations
  validates :phone_number, format: { with: /\A(?:(?:\+|00)33[\s.-]{0,3}(?:\(0\)[\s.-]{0,3})?|0)[1-9](?:(?:[\s.-]?\d{2}){4}|\d{2}(?:[\s.-]?\d{3}){2})\z/, message: "Merci de renseigner un numéro de téléphone valide" }
  
  def past_appointments
    past_appointments_array = []
    self.appointments.order("created_at DESC").each do |appointment|
      if appointment.slot.start_date < DateTime.now
        past_appointments_array << appointment
      end
    end
    return past_appointments_array
  end

  def future_appointments
    future_appointments_array = []
    self.appointments.order("created_at DESC").each do |appointment|
      if appointment.slot.start_date > DateTime.now
        future_appointments_array << appointment
      end
    end
    return future_appointments_array
  end

  def self.from_omniauth(access_token)
    data = access_token.info
    user = User.where(email: data['email']).first

    unless user
      user = User.create(
        email: data['email'],
        password: Devise.friendly_token[0, 20]
      )
    end
    user
  end

  def add_default_picture
    unless profile_picture.attached?
      self.profile_picture.attach(
        io: File.open(
          Rails.root.join('app', 'assets', 'images', 'profile_placeholder.png')
        ),
        filename: 'profile_placeholder.png',
        content_type: 'image/png'
      )
    end
  end

  private

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end
  
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def google_oauth2
    @user = User.from_omniauth(request.env['omniauth.auth'])
    if @user.persisted?
      flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
      sign_in_and_redirect @user, event: :authentication
    else
      session['devise.google_data'] = request.env['omniauth.auth'].except('extra')
      redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_same_user, :authenticate_user!

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    
    edited_user = params[:user]

    if @user.update(first_name: edited_user[:first_name], last_name: edited_user[:last_name], phone_number: edited_user[:phone_number])
      flash[:success] = "Votre profil a été édité avec succès 👌"
      redirect_to user_path(@user)
    else
      flash.now[:warning] = @user.errors.full_messages
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    if params[:admin] 
      flash[:success] = "Utilisateur supprimé avec succès. 💪"
      redirect_to admin_root_path
    else
      flash[:success] = "Votre compte a été supprimé avec succès. Nous espérons vous revoir bientôt 👋"
      redirect_to root_path
    end
  end

  private

  def is_same_user
    @user = User.find(params[:id])
    if @user == current_user
    elsif current_user.is_admin?
    else
      flash[:warning] = "Vous n'êtes pas autorisé à accéder à cette page ⛔"
      redirect_to root_path
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper

  def is_admin?
    unless current_user.is_admin
      flash[:danger] = "Accès refusé. Vous n'êtes pas administrateur de ce site ⛔"
      redirect_to root_path
    end
  end

end

app/views/users/_appointment-card.html.erb
<div class="appointment-card">
  <div class="appointment-card__picture">
    <%if appointment.property.property_picture.attached?%>
      <%= image_tag appointment.property.property_picture, alt: 'property_picture' %>
    <%else%>
      <div class="appointment-card__picture__no-picture">
        <p>Pas de photo du logement</p>
      </div>
    <%end%>
  </div>
  <div class="appointment-card__text">
    <p><%= appointment.property.title %></p>
    <p class="mb1"><%= appointment.property.city %></p>
    <%if appointment.is_interested == false %>
      <p><small>⚠️ Vous avez indiqué ne pas être intéressé(e) par ce logement</small></p>
    <%elsif appointment.is_accepted == false %> 
      <p><small>⚠️ Votre candidature n'a pas été retenue</small></p>
    <%elsif appointment.is_accepted == true %>
      <%if appointment.property.owner_project == "rent"%>
        <p class="green"><small>🥳 Votre dossier a été accepté !</small></p>
      <%else%>
        <p class="green"><small>🥳 Votre offre a été acceptée !</small></p>
      <%end%>
    <%else%>
      <%if appointment.property.owner_project == "rent"%>
        <% if appointment.candidate_dossierfacile_folder.attached? || appointment.candidate_dossierfacile_link && appointment.candidate_dossierfacile_link != "" %>
          <p class="green"><small>✔️ Dossier de location complet</small></p>
        <% elsif appointment.candidate_documents.attached? && appointment.candidate_documents.size == 5 %>
          <p class="green"><small>✔️ Dossier de location complet</small></p>
        <%else%>
          <p class="danger"><small>⚠️ Dossier de location incomplet</small></p>
        <%end%>
      <%end%>
      <%if appointment.slot_id != nil %>
        <%if appointment.slot.start_date > DateTime.now %>
          <p><small>Prochaine visite prévue le <%= appointment.slot.start_date.strftime("%d/%m") %> à <%= appointment.slot.start_date.strftime("%H:%M") %></small></p>
        <%else%>
          <p><small>Dernière visite réalisée le <%= appointment.slot.start_date.strftime("%d/%m") %></small></p>
        <%end%>
      <%else%>
        <p><small>Aucune visite programmée</small></p>
      <%end%>
    <%end%>
  </div>
</div>

app/views/users/_property-card.html.erb
<div class="property-card">
  <div class="property-card__picture <%= unpaid ? ('unpaid') : nil %>">
    <%if property.property_picture.attached?%>
      <%= image_tag property.property_picture, alt: 'property_picture' %>
    <%else%>
      <div class="property-card__picture__no-picture">
        <p>Ajoutez une photo en éditant votre logement</p>
      </div>
    <%end%>
  </div>
  <div class="property-card__text">
    <p><%= property.title %></p>
    <p class="mb1"><%= property.city %></p>
    <p class="primary"><small><%= property.candidates.size %> <%= property.candidates.size > 1 ? "candidatures" : "candidature" %></small></p>
    <%if property.slots.size > 0 %>
      <%if property.slots.order("start_date DESC")[0].start_date > DateTime.now%>
        <p><small>Prochaine visite prévue le <%= property.slots.order("start_date DESC")[0].start_date.strftime("%d/%m") %> à <%= property.slots.order("start_date DESC")[0].start_date.strftime("%H:%M") %></small></p>
      <%else%>
        <p><small>Dernière visite réalisée le <%= property.slots.order("start_date DESC")[0].start_date.strftime("%d/%m") %> à <%= property.slots.order("start_date DESC")[0].start_date.strftime("%H:%M") %></small></p>
      <%end%>
    <%else%>
      <p><small>Aucune visite programmée</small></p>
    <%end%>
  </div>
</div>

app/views/users/edit.html.erb
<div class="form-page">
  <div class="form-page__form">
    <h2>Éditer mon profil</h2>

    <%= form_with model: @user, url: user_path(@user), local: true, class: "form", id: "item-form", multipart: true do |f| %>
    
      <div class="form-group">
        <%= f.label 'Prénom', class: "form-label" %>
        <%= f.text_field :first_name, class: "form-control", autofocus: true, autocomplete: "first_name" %>
      </div>

      <div class="form-group">
        <%= f.label 'Nom', class: "form-label" %>
        <%= f.text_field :last_name, class: "form-control", autofocus: true, autocomplete: "last_name" %>
      </div>

      <div class="form-group">
        <%= f.label 'Tél', class: "form-label" %>
        <%= f.text_field :phone_number, class: "form-control", autofocus: true, autocomplete: "phone_number" %>
      </div>

      <div class="actions mb1">
        <%= f.submit "Enregistrer les changements", class:"btn white-btn bg-primary" %>
      </div>
    <% end %>

    <div class="form-page__form--links">
      <p class="mb1"><%= link_to 'Modifier mon e-mail ou mot de passe', edit_user_registration_path(@user), class:"primary" %></p>
      <p><%= link_to 'Retour', user_path(@user) %></p>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="profile-wrapper">
  <%= link_to raw("<i class='fas fa-chevron-left'></i> Retourner à l'accueil "), root_path, class: "return-link" %>

  <h2> Mon profil </h2>
  
  <div class="profile-wrapper__informations">
    <div class="profile-wrapper__informations__left">
      <p>
        <span class='text-muted'>Prénom&nbsp;:</span>
        <%= @user.first_name %>
      </p>
      <p>
        <span class='text-muted'>Nom&nbsp;:</span>
        <%= @user.last_name %>
      </p>
      <p>
        <span class='text-muted'>Tél&nbsp;:</span>
        <%if @user.phone_number %>
          <%= @user.phone_number %>
        <%end%>
      </p>
      <p>
        <span class='text-muted'>Adresse e-mail&nbsp;:</span>
        <%= @user.email %>
      </p>
    </div>
    <%if @user.profile_picture.attached? %>
      <div>
        <div class="pic profile-wrapper__informations__right">
          <%= image_tag @user.profile_picture, alt: 'profile_picture' %>
          <p class="profile-wrapper__informations__right--change"> Modifier </p>
        </div>
        <%if @user.profile_picture.filename != 'profile_placeholder.png' %>
          <%= link_to "Supprimer la photo", user_profile_picture_path(current_user), method: "delete", class: "delete-profile-picture"  %>
        <%end%>
      </div>
    <%end%>
    <%= render(
      partial: 'layouts/picture_modal',
      locals: {
        url: user_profile_pictures_path(@user),
        type: :profile_picture
      }
    ) %>
  </div>
  <p><%= link_to "Éditer mon profil", edit_user_path(@user), class: "btn white-btn bg-primary" %></p>

  <% if @user.properties.count == 0 && @user.appointments.count == 0 %>

    <h2> Vous souhaitez vendre ou louer un logement&nbsp;? </h2>
    <p><%= link_to "Enregistrer mon logement", new_property_path, class: "btn white-btn bg-primary" %></p>

    <h2> Vous souhaitez répondre à une annonce&nbsp;? </h2>
    <p class="mb2">Rendez-vous directement sur l’annonce en ligne (Leboncoin, PaP, SeLoger, etc.) et suivez le lien immolib renseigné par le propriétaire.</p>

  <% end %>

  <% if @user.properties.count > 0 %>

    <h2> Mes logements </h2>

    <div class="properties-wrapper">
      <% @user.properties.order("created_at DESC").each do |p| %>
        <div class="property">
          <%= link_to render(partial: 'property-card', locals: {property: p, unpaid: false}), property_path(p) %>
        </div>
      <% end %>
    </div>

    <h2> Vous souhaitez vendre ou louer un autre logement&nbsp;? </h2>
    <p><%= link_to "Enregistrer mon logement", new_property_path, class: "btn white-btn bg-primary" %></p>

  <% end %>

  <% if @user.appointments.count > 0 %>

    <h2> Mes candidatures </h2>
    
    <div class="properties-wrapper">
      <% @user.appointments.order("created_at DESC").each do |appointment| %>
        <%= link_to render(partial: 'appointment-card', locals: {appointment: appointment} ), appointment_path(appointment) %>
      <% end %>
    </div>

    <% if @user.properties.count == 0 %>
      <h2> Vous souhaitez vendre ou louer un logement&nbsp;? </h2>
      <p class="mb2"><%= link_to "Enregistrer mon logement", new_property_path, class: "btn white-btn bg-primary" %></p>
    <% end %>

  <% end %>
</div>