config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'static_pages#home'

  get "welcome_user", to: "static_pages#welcome_user"
  get "faq", to: "static_pages#faq"

  resources 'users' do
    resources 'profile_pictures', only: [:create, :destroy]
  end

  resources 'properties' do
    get 'share', to: "properties#share" 
    get 'candidate_details', to: 'properties#show_candidate_details', as: 'candidate_details'
    delete 'delete-visits', to: "properties#destroy_all_slots" 
    resources 'property_pictures', only: [:create, :destroy]
    resources 'slots' do
      get 'candidate_details', to: 'slots#show_candidate_details', as: 'candidate_details'
    end
    member do
      #new candidate process
      get 'go-visit', to: "new_candidates#welcome_candidate"
      get 'step-1', to: "new_candidates#step1_login"
      get 'step1', to: "new_candidates#step1_logout"
      get 'step-2', to: "new_candidates#step2"
      get 'step-3', to: "new_candidates#step3"
    end
  end

  resources 'appointments', only: [:create, :show, :destroy] do
    resources 'candidate_slots', only: [:update, :destroy]
    resources 'candidate_messages', only: [:edit, :update, :destroy]
    resources 'candidate_documents', only: [:create, :destroy]
    resources 'candidate_dossierfacile_folders', only: [:create, :destroy]
    resources 'candidate_dossierfacile_links', only: [:create, :destroy]
    resources 'candidate_decisions', only: [:update]
    resources 'owner_decisions', only: [:update]
  end

  # scope '/checkout' do
  #   resources 'checkout', only: [:create]
  #   get 'success', to: 'checkout#success', as: 'checkout_success'
  #   get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
  # end

  namespace :admin do
    root 'welcome#index'
  end

end

app/models/property.rb
class Property < ApplicationRecord
  #Callbacks
  before_create :randomize_property_id
  before_validation :create_stripe_product
  after_commit :add_default_picture, on: [:create, :update]

  #Associations
  belongs_to :owner, class_name: "User"
  has_many :slots, dependent: :destroy
  has_many :appointments#, through: :slots
  has_many :candidates, class_name: "User", through: :appointments
  has_one_attached :property_picture, dependent: :destroy
  
  #Validations
  validates :title, presence: true, length: { in: 3..140 }
  validates :city, presence: true
  #validates :zip_code, presence: true, format: { with: /\A(([0-8][0-9])|(9[0-5])|(2[ab]))[0-9]{3}\z/, message: "Veuillez entrer un code postal valide" } 
  validates :other_link, format: URI::regexp(%w[http https]), allow_blank: true
  validates :owner_project, presence: true, allow_blank: false
  validates :property_picture, size: {less_than: 3.megabytes, message: 'must be less than 3MB'}

  def go_visit_url
    @id = self.id
    return "https://immolib.herokuapp.com/properties/#{@id}/go-visit"
  end
  
  def go_visit_url_short
    @id = self.id
    return "immolib.herokuapp.com/properties/#{@id}/go-visit"
  end

  def go_visit_url_dev
    @id = self.id
    return "https://immolib-dev.herokuapp.com/properties/#{@id}/go-visit"
  end

  def go_visit_url_local
    @id = self.id
    return "localhost:3000/properties/#{@id}/go-visit"
  end

  def already_has_appointment?(user)
    result = false
    self.candidates.each do |cand|
      if cand == user
        result = true
      end
    end
    return result
  end

  def has_available_slot?
    ans = false
    self.slots.each do |slot|
      unless slot.is_past?
        slot.available? ? (return ans = true) : nil
      end
    end
    return ans
  end

  def available_slots
    count = 0
    self.slots.each do |slot|
      unless slot.is_past?
        if slot.available?
          count += 1
        end
      end
    end
    return count
  end

  def can_book?(candidate)
    self.slots.each do |slot|
      unless slot.is_past? 
        slot.candidates.include?(candidate) ? (return false) : nil
      end
    end
    return true
  end
  #slot.candidates.include?(current_user)

  def future_slots
    future_slots_array = []
    self.slots.each do |slot|
      if slot.start_date > DateTime.now
        future_slots_array << slot
      end
    end
    return future_slots_array
  end

  def has_future_slots?
    result = false
    if self.future_slots.size > 0
      return result = true
    end
    return result
  end

  private

  def stripe_price
    Stripe::Price.retrieve(self.stripe_price_id)
  end

  def stripe_product
    Stripe::Product.retrieve(self.stripe_price.product)
  end

  def add_default_picture
    unless property_picture.attached?
      self.property_picture.attach(
        io: File.open(
          Rails.root.join('app', 'assets', 'images', 'property_placeholder.png')
        ),
        filename: 'property_placeholder.png',
        content_type: 'image/png'
      )
    end
  end

  def randomize_property_id
    begin
      self.id = SecureRandom.random_number(1_000_000)
    end while Property.where(id: self.id).exists?
    #self.id = 5.times.map { rand(1..9) }.join.to_i
  end

  def create_stripe_product
    unless self.stripe_price_id
      stripe_product = Stripe::Product.create({
        name: "1 logement immolib",
        description: "#{title} - #{city}"
      })

      # Stripe::Product.update(
      #   stripe_product.id,
      #   {images: [image_url]},
      # ) if self.image_url !=""

      stripe_price = Stripe::Price.create({
        product: stripe_product.id,
        unit_amount: 2999,
        currency: 'eur'
      })

      self.stripe_price_id = stripe_price.id

      self.save
    end
  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :authenticate_user!
  before_action :is_owner?, only: [:show, :edit, :update, :destroy]

  # user as potential ower

  def new
    @property = Property.new
  end 

  def create
    @property = Property.new(property_params)
    @property.owner = current_user
    
    if @property.save
      flash[:success] = "La présentation de votre logement a été réalisée avec succès ✌️"
      redirect_to(property_slots_path(@property))
    else
      flash.now[:warning] = @property.errors.full_messages
      render :new
    end
  end
  
  def share
    @property = Property.find(params[:property_id])
    UserMailer.new_property_validation_email(@property).deliver_now
  end

  # user as owner

  def index
    @properties = current_user.properties
  end

  def show
    @property = Property.find(params[:id])
    @date_arr = ["", "jan.", "fév.", "mar.", "avr.", "mai", "juin", "juil.", "août", "sept.", "oct.", "nov.", "déc."]

    respond_to do |format|
      format.html
      format.js
    end
  end 

  def show_candidate_details
    @appointment = Appointment.find(params[:appointment])
    respond_to do |format|
      format.js {}
    end
  end

  def edit
    @property = Property.find(params[:id])
  end

  def update
    @property = Property.find(params[:id])
    
    edited_property = params[:property]

    if @property.update(title: edited_property[:title], city: edited_property[:city], other_link: edited_property[:other_link], instructions: edited_property[:instructions])
      flash[:success] = "Votre annonce a été éditée avec succès 👌"
      redirect_to property_path(@property)
    else
      flash.now[:warning] = @property.errors.full_messages
      render :edit
    end
  end

  def destroy
    @property = Property.find(params[:id])
    @property.destroy
    if current_user.is_admin?
      flash[:success] = "Le logement a bien été supprimé 👌"
      redirect_to admin_root_path
    elsif @property.is_paid
      flash[:success] = "Votre logement a bien été supprimé. Les candidats inscrits à une visite à venir sont automatiquement prévenus 👌"
      redirect_to user_path(current_user)
    else 
      flash[:success] = "Votre logement a bien été supprimé 👌"
      redirect_to user_path(current_user)
    end
  end

  def destroy_all_slots
    property = Property.find(params[:property_id])

    #update apt with future slots to nil
    property.appointments.each do |appointment|
      if appointment.slot_id != nil && !appointment.slot.is_past?
        appointment.update(slot_id: nil)
      end
    end

    #delete slots
    future_slots = property.future_slots
    Slot.destroy(future_slots.map(&:id))
    flash[:success] = "Les créneaux de visite à venir ont été supprimés avec succès 👌"
    redirect_to property_path(property)
  end

  private

  def property_params
    params.require(:property).permit(:owner_project, :title, :city, :property_picture, :other_link, :instructions)
  end

  def is_owner?
    @property = Property.find(params[:id])
    if @property.owner == current_user
    elsif current_user.is_admin?
    else
      flash[:warning] = "Vous n'avez pas l'autorisation d'accéder à cette page ⛔"
      redirect_to root_path
    end
  end
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/properties/_calendar.html.erb
<div class='calendar-wrapper'>
  <%= week_calendar(events: @property.slots, attribute: :start_date) do |date, slots| %>
    <div class="property-wrapper__right__date">
      <%= date.strftime("%d") %> <%= @date_arr[date.strftime("%m").to_i]%>
    </div>
    <% slots.each do |slot| %>
      <%= link_to render(partial: "slot-card", locals: { slot: slot }), property_slot_path(@property, slot) %>
    <% end %>
  <% end %>
</div>

app/views/properties/_candidate_list.html.erb
<div class="candidates-wrapper__content__candidate c<%= a.candidate.id %> <%= first ? "active" : nil %>">
  <h3> 
    <%= a.candidate.first_name && a.candidate.last_name ? ("#{a.candidate.first_name} #{a.candidate.last_name}") : a.candidate.email %> 
    <span class="candidates-wrapper__content__candidate--subtitle"> - Fiche candidat </span>
  </h3>
</div>

app/views/properties/_new_property_form.html.erb
<div class="container">
  <div class="text-center section-title">
    <h1>Etape 1/3 : renseignez les informations clés de votre logement</h1>
    <p class="mt2">Vous pourrez les modifier ou les compléter à tout moment dans votre espace immolib</p>
  </div>
  <div class="form-page">
    <div class="form-page__form">
      <p class='toggle-label bolder'>Je souhaite *</p>
      <div class='sell-rent-wrapper'>
        <p>Louer</p>
        <div class='sell-rent-toggle'>
          <button class='rent-btn'></button>
          <button class='sell-btn'></button>
          <div></div>
        </div>
        <p>Vendre</p>
      </div>
      <%= form_with model: property, url: properties_path, local: true, class: "form", id: "item-form", multipart: true do |f| %>
        <%= f.hidden_field :owner_project %>
        <div class="form-group mb2">
          <%= f.label "Titre du logement *", class: "form-label bolder" %>
          <p><small>💡 Uniformisez le titre avec celui de vos annonces en ligne (ex : PaP)</small></p>
          <%= f.text_field :title, class: "form-control", placeholder: "Donnez un titre à votre logement", required: true %>
        </div>
        <div class="form-group mb2">
          <%= f.label "Ville *", class: "form-label bolder" %>
          <p><small>💡 Précisez le code postal entre parenthèses</small></p>
          <%= f.text_field :city, class: "form-control", placeholder: "Indiquez la ville de votre logement", required: true %>
        </div>
        <div class="form-group mb2">
          <%= f.label "Photo de votre logement", class: "form-label bolder" %>
          <p class="mb1"><small>💡 Choisissez la photo la plus représentative de votre logement</small></p>
          <%= f.file_field :property_picture, is: "drop-files", label: "Télécharger une photo de votre logement", help: "Vous pouvez la glisser-déposer ici", accept: 'image/png,image/gif,image/jpeg' %>
        </div>
        <div class="form-group mb2">
          <%= f.label "Lien d'une de vos annonces en ligne", class: "form-label bolder" %>
          <p><small><i class="fas fa-info-circle"></i> Ce lien permettra aux candidats d'accéder facilement aux détails de votre annonce</small></p>
          <%= f.text_field :other_link, class: "form-control", placeholder: "Copiez-collez l'URL d'une annonce en ligne (ex : PaP)" %>
        </div>
        <div class="form-group mb2">
          <%= f.label "Instructions pour les visites", class: "form-label bolder" %>
          <p><small><i class="fas fa-info-circle"></i> Ces instructions seront automatiquement communiquées aux candidats à l'approche d'une visite</small></p>
          <%= f.text_area :instructions, class: "form-control", placeholder: "Indiquez ici les modalités logistiques pour les visites : adresse, digicode, interphone, etc." %>
        </div>
        <div>
          <%= f.submit "Valider et passer à l'étape suivante", class: "btn white-btn bg-primary" %>
        </div>
      <%end%>
    </div>
  </div>
</div>

<%= javascript_include_tag 'sell-rent-toggle' %>

app/views/properties/_property_intro.html.erb
<div class="candidate-section-title">
  <h1 class="primary">Mon logement</h1>
</div>
<h3 class="bolder"><%= property.title%></h3>
<p><%= property.city%></p>
<div class="card-white">
  <p class="mb2">💡 <span class="bolder">Partagez votre lien immolib : les candidats n'auront plus qu'à suivre un parcours simple et rapide&nbsp;!</span></p>
  <div class="url-container mb1">
    Message à partager sur vos <span class="text-muted">annonces en ligne</span> (ex : PaP) :
    <p class="link">
      <em>
      <% if property.owner_project == "rent" %>
        <a>Copiez-collez ce lien dans votre navigateur pour réserver un créneau de visite et transmettre votre dossier de location : <span class="bolder"><%= property.go_visit_url_short %></span></a>
      <%else%> 
        <a>Copiez-collez ce lien dans votre navigateur pour réserver un créneau de visite : <span class="bolder"><%= property.go_visit_url_short %></span></a>
      <%end%> 
      </em>
      <i class="far fa-copy">
        <span class="copy-text"> Copier </span>
      </i>
    </p>
  </div>
  <div class="url-container mb1">
    Message à partager par <span class="text-muted">email</span>, <span class="text-muted">SMS</span> ou sur vos <span class="text-muted">réseaux sociaux</span> :
    <p class="link"> 
      <em>
      <% if property.owner_project == "rent" %>
        <a>Suivez ce lien pour réserver un créneau de visite et transmettre votre dossier de location : <span class="bolder"><%= property.go_visit_url %></span></a>
      <%else%> 
        <a>Suivez ce lien pour réserver un créneau de visite : <span class="bolder"><%= property.go_visit_url %></span></a>
      <%end%> 
      </em>
      <i class="far fa-copy">
        <span class="copy-text"> Copier </span>
      </i>
    </p>
  </div>
  <hr class="hr-grey mw80 mt2 mb2">
  <%= link_to "Mon logement", "#property-section-1", class: "btn outline-btn-white" %>
  <%= link_to "Mes visites", "#property-section-2", class: "btn outline-btn-white" %>
  <%= link_to "Mes candidats", "#property-section-3", class: "btn outline-btn-white" %>
</div>
<% unless property.candidates.size > 0 %>
  <p class="mt1"><%= link_to "Supprimer mon logement", property_path(property), method: "delete", data: {confirm: "Êtes-vous sûr ? Cette action est irréversible."}, class:"btn small-btn white-btn bg-warning"%></p>
<%end%>

app/views/properties/edit.html.erb
<%= link_to raw("<i class='fas fa-chevron-left'></i> Retour"), property_path(@property), class: "return-link pt1 pl4" %>
<div class="form-page">
  <div class="form-page__form">
    <h2>Éditer mon logement</h2>

    <%= form_with model: @property, url: property_path(@property), local: true, class: "form", id: "item-form", multipart: true do |f| %>
    
      <div class="field">
        <%= f.label 'Titre *', class: "form-label bolder" %><br />
        <p><small>💡 Uniformisez le titre avec celui de vos annonces en ligne (ex : PaP)</small></p>
        <%= f.text_field :title, autofocus: true, autocomplete: "title", required: true %>
      </div>

      <div class="field">
        <%= f.label 'Ville *', class: "form-label bolder" %>
        <p><small>💡 Précisez le code postal entre parenthèses</small></p>
        <%= f.text_field :city, autofocus: true, autocomplete: "city", required: true %>
      </div>

      <div class="field">
        <%= f.label 'Lien vers une annonce en ligne', class: "form-label bolder" %>
        <p><small><i class="fas fa-info"></i> Ce lien permet aux candidats d'accéder facilement aux détails de votre annonce</small></p>
        <%= f.text_field :other_link, autofocus: true, autocomplete: "other_link" %>
      </div>

      <div class="field">
        <%= f.label 'Instructions pour les visites', class: "form-label bolder" %>
        <p><small><i class="fas fa-info"></i> Ces instructions seront automatiquement communiquées aux candidats à l'approche d'une visite (ex : adresse, digicode, interphone, etc.)</small></p>
        <%= f.text_area :instructions, autofocus: true, autocomplete: "instructions" %>
      </div>

      <div class="actions mb1">
        <%= f.submit "Enregistrer les changements", class:"btn white-btn bg-primary" %>
      </div>
    <% end %>

  </div>
</div>

app/views/properties/message_candidate.html.erb
<div class="pt4 text-center">
  <h1>Étape 2/2 : Parlez-moi de votre projet 🙂 (optionnel)</h1>
  <h3>Écrivez-moi quelques lignes pour me parler de vous et de votre projet</h3>
</div>
<div class="form-page">
  <div class="form-page__form">
    <p class="mb2 text-center">Ce message est optionnel mais vivement encouragé afin de connaître davantage votre projet et anticiper au mieux votre visite et vos éventuelles questions.</p>
    <p class="mb2 text-center"><em>Vous pourrez le modifier ou le supprimer à tout moment depuis votre espace immolib.</em></p>
    <%= form_with model: @appointment, url: appointment_path(@appointment), method: "patch", local: true, class: "form", id: "item-form", multipart: true do |f| %>
      <div class="form-group">
        <%= f.text_area :candidate_message, class: "form-control", placeholder: "Rédigez ici votre message au propriétaire", maxlength: "1000" %>
      </div>
      <div>
        <%= f.submit "Finaliser ma candidature", class: "btn white-btn bg-primary" %>
      </div>
    <%end%>
    <div class="text-center pt1">
      <p>
        <em>Un email de confirmation vous sera envoyé avec toutes les modalités logistiques pour la visite. 
        Je vous invite à <span class="bolder">compléter votre profil</span> : avec une photo c’est toujours plus sympa !
        En cas d’imprévu, merci de bien vouloir modifier ou annuler votre inscription directement depuis votre espace en ligne.</em>
      </p>
    </div>
  </div>
</div>

app/views/properties/new.html.erb
<%= render(
  partial: 'new_property_form',
  locals: { property: @property }
) %>

app/views/properties/show.html.erb
<%= link_to raw("<i class='fas fa-chevron-left'></i> Retour"), user_path(current_user), class: "return-link ml4 pt1" %>
<div class="container-small text-center">
  <%= render partial:"property_intro", locals: {property: @property} %>
</div>
<div class="container">
  <hr/>
</div>
<div class="container-small text-center" id='property-section-1'>
  <h1 class="primary mb2">Mon logement</h1>
    <p class="mb2">💡 <span class="bolder">Complétez les informations sur votre logement pour faciliter le parcours d'inscription des candidats <span class="bolder"></p>
    <%if @property.property_picture.attached? %>
      <div>
        <div class="pic property-picture">
          <%= image_tag @property.property_picture, alt: 'property picture' %>
          <p class="property-picture--change"> Modifier </p>
        </div>
        <%if @property.property_picture.filename != 'property_placeholder.png' %>
          <%= link_to "Supprimer la photo", property_property_picture_path(@property), method: "delete", class: "delete-property-picture pt1"  %>
        <%end%>
      </div>
    <%end%>
    <%= render(
      partial: 'layouts/picture_modal',
      locals: {
        url: property_property_pictures_path(@property),
        type: :property_picture
      }
    ) %>
    <div class="mt2">
      <div class="card-white-small">
        <p class="bolder"><i class="far fa-arrow-alt-circle-right"></i> Titre</p>
        <p><%= @property.title %> <%= link_to raw("<i class='fas fa-edit'></i>"), edit_property_path(@property) %></p>
      </div>
      <div class="card-white-small">
        <p class="bolder"><i class="far fa-arrow-alt-circle-right"></i> Ville</p>
        <p><%= @property.city %> <%= link_to raw("<i class='fas fa-edit'></i>"), edit_property_path(@property) %></p>
      </div>
      <div class="card-white-small">
        <p class="bolder"><i class="far fa-arrow-alt-circle-right"></i> Lien d'une annonce en ligne</p>
        <p class="mb1"><small><i class="fas fa-info"></i> Ce lien permettra aux candidats d'accéder facilement aux détails de votre annonce</small></p>
        <% if @property.other_link == "" %>
          <p><small><em>⚠️  Editez votre logement pour indiquer le lien vers une annonce en ligne (ex : PaP)</em></small></p>
        <% else %>
          <p><%= link_to @property.other_link, @property.other_link, target: '_blank' %> <%= link_to raw("<i class='fas fa-edit'></i>"), edit_property_path(@property) %></p>
        <% end %>
      </div>
      <div class="card-white-small">
        <p class="bolder"><i class="far fa-arrow-alt-circle-right"></i> Indications pour les visites</p>
        <p class="mb1"><small><i class="fas fa-info"></i> Ces informations seront automatiquement communiquées aux candidats à l'approche d'une visite</small></p>
        <% if @property.instructions == "" %>
          <p><small><em>⚠️  Editez votre logement pour renseigner vos indications aux candidats (adresse, digicode, interphone, etc.) </em></small></p>
        <% else %>
          <p><em><%= simple_format(@property.instructions) %></em> <%= link_to raw("<i class='fas fa-edit'></i>"), edit_property_path(@property) %></p> 
        <% end %>
        <% if @property.owner.phone_number %>
          <p class="mt2">En cas de problème, les candidats pourront vous contacter sur le n° suivant : <span class="primary"><%= @property.owner.phone_number %></span> <%= link_to raw("<i class='fas fa-edit'></i>"), edit_user_path(@property.owner) %></p>
        <% else %>
          <p class="mt2">💡 Pour faciliter les échanges avec les candidats, indiquez un numéro de téléphone en complétant vos <%= link_to "informations personnelles", edit_user_path(@property.owner) %></p>
        <% end %>
      </div>
    </div>
    <p><%= link_to "Éditer mon logement", edit_property_path(@property), class:"btn white-btn bg-primary" %></p>
  </div>
</div>
<div class="container">
  <hr/>
</div>
<div class="container-small text-center" id='property-section-2'>
  <h1 class="primary mb2">Mes visites</h1>
  <div class="mb2">
    <% if @property.owner_project == "rent" %>
      <p>💡 <span class="bolder">Cliquez sur un créneau à venir pour voir la liste des candidats inscrits et leur dossier<span class="bolder"></p>
    <% else %>
      <p>💡 <span class="bolder">Cliquez sur un créneau à venir pour voir la liste des candidats inscrits et leur profil<span class="bolder"></p>
    <% end %>
    <% if @property.has_available_slot? == false %>
      <p class="mt2 danger"><small><em>⚠️  Aucun créneau de visite disponible <br/> Pour éviter de passer à côté de nouveaux candidats, ajoutez des créneaux et/ou augmentez le nombre de places maximum des créneaux à venir</em></small><p>
    <% end %>  
  </div>
  <%= render(partial: 'calendar') %>
  <p class="mt2"><%= link_to 'Ajouter un créneau de visite', new_property_slot_path(@property, redirect_path: "existing_property"), class:"btn white-btn bg-primary" %><p>
  <% if @property.has_future_slots? %>
    <p><%= link_to 'Supprimer tous les créneaux à venir', property_delete_visits_path(@property), method: "delete", data: {confirm: "Êtes-vous sûr ? Cette action est irréversible."}, class:"btn small-btn white-btn bg-warning" %><p>
    <p><small><em><i class="fas fa-info-circle"></i> Les candidats inscrits à un créneau à venir seront automatiquement prévenus par email</em></small></p>
  <% end %> 
</div>
<div class="container">
  <hr/>
</div>
<div class="container-small" id='property-section-3'>
  <h1 class="primary mb2 text-center">Mes candidats</h1>
  <% if @property.candidates.size > 0 %>
    <p class="mb1 text-center">💡 <span class="bolder">Cliquez sur un candidat pour voir sa fiche détaillée</span></p>
    <div class="candidates-wrapper pl2 pr2">
      <div class="candidates-wrapper-left">
        <div class="candidates-wrapper__content">
          <% firstCandidate = true %>
          <% @property.appointments.order("created_at DESC").each do |a| %>
            <%= link_to render(partial: "candidate_list", locals: {a: a, first: firstCandidate}), property_candidate_details_path(@property, appointment: a), remote: true %>
            <% firstCandidate = false %>
          <% end %>
        </div>
      </div>
      <div class="candidates-wrapper-right">
        <%= render(partial: "show_candidate_details", locals: {appointment: @property.appointments.first}) %>
      </div>
    </div>
  <% else %>
    <div class="text-center">
      <p class="mb2"><small><em> Vous n'avez pas encore de candidats pour ce logement</em></small></p>
      <div class="card-white">
        <p class="mb2">💡 <span class="bolder">Partagez votre lien immolib : les candidats n'auront plus qu'à suivre un parcours simple et rapide&nbsp;!</span></p>
        <div class="url-container mb1">
          Message à partager sur vos <span class="text-muted">annonces en ligne</span> (ex: PaP) :
          <p class="link">
            <em>
            <% if @property.owner_project == "rent" %>
              <a>Copiez-collez ce lien dans votre navigateur pour réserver un créneau de visite et transmettre votre dossier de location : <span class="bolder"><%= @property.go_visit_url_short %></span></a>
            <%else%> 
              <a>Copiez-collez ce lien dans votre navigateur pour réserver un créneau de visite : <span class="bolder"><%= @property.go_visit_url_short %></span></a>
            <%end%> 
            </em>
            <i class="far fa-copy">
              <span class="copy-text"> Copier </span>
            </i>
          </p>
        </div>
        <div class="url-container">
          Message à partager par <span class="text-muted">email</span>, <span class="text-muted">SMS</span> ou sur vos <span class="text-muted">réseaux sociaux</span> :
          <p class="link"> 
            <em>
            <% if @property.owner_project == "rent" %>
              <a>Suivez ce lien pour réserver un créneau de visite et transmettre votre dossier de location : <span class="bolder"><%= @property.go_visit_url %></span></a>
            <%else%> 
              <a>Suivez ce lien pour réserver un créneau de visite : <span class="bolder"><%= @property.go_visit_url %></span></a>
            <%end%> 
            </em>
            <i class="far fa-copy">
              <span class="copy-text"> Copier </span>
            </i>
          </p>
        </div>
      </div>
      <% if @property.has_available_slot? == false %>
        <p><small><em>⚠️  Vous n'avez pas indiqué de créneaux de visite pour ce logement</em></small></p>
        <%= link_to 'Ajouter un créneau de visite', new_property_slot_path(@property, redirect_path: "existing_property"), class:"btn small-btn white-btn bg-primary" %>
      <% else %>
        <p><small><em>💡  Ajoutez de nouveaux créneaux de visites pour optimiser le nombre de candidats </em></small></p>
        <%= link_to 'Ajouter un créneau de visite', new_property_slot_path(@property, redirect_path: "existing_property"), class:"btn small-btn white-btn bg-primary" %>
      <% end %>
    </div>
  <% end %>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.8.0/gsap.min.js"></script>
<%= javascript_include_tag 'clipboard' %>

app/views/properties/show.js.erb
document
  .getElementById('calendar')
  .innerHTML = "<%= j render(partial: 'calendar', locals: { instructions: false }) %>";