config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'static_pages#home'

  get "welcome_user", to: "static_pages#welcome_user"
  get "faq", to: "static_pages#faq"

  resources 'users' do
    resources 'profile_pictures', only: [:create, :destroy]
  end

  resources 'properties' do
    get 'share', to: "properties#share" 
    get 'candidate_details', to: 'properties#show_candidate_details', as: 'candidate_details'
    delete 'delete-visits', to: "properties#destroy_all_slots" 
    resources 'property_pictures', only: [:create, :destroy]
    resources 'slots' do
      get 'candidate_details', to: 'slots#show_candidate_details', as: 'candidate_details'
    end
    member do
      #new candidate process
      get 'go-visit', to: "new_candidates#welcome_candidate"
      get 'step-1', to: "new_candidates#step1_login"
      get 'step1', to: "new_candidates#step1_logout"
      get 'step-2', to: "new_candidates#step2"
      get 'step-3', to: "new_candidates#step3"
    end
  end

  resources 'appointments', only: [:create, :show, :destroy] do
    resources 'candidate_slots', only: [:update, :destroy]
    resources 'candidate_messages', only: [:edit, :update, :destroy]
    resources 'candidate_documents', only: [:create, :destroy]
    resources 'candidate_dossierfacile_folders', only: [:create, :destroy]
    resources 'candidate_dossierfacile_links', only: [:create, :destroy]
    resources 'candidate_decisions', only: [:update]
    resources 'owner_decisions', only: [:update]
  end

  # scope '/checkout' do
  #   resources 'checkout', only: [:create]
  #   get 'success', to: 'checkout#success', as: 'checkout_success'
  #   get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
  # end

  namespace :admin do
    root 'welcome#index'
  end

end

app/views/layouts/_flash.html.erb
<% flash.each do |type, msg| %>
  <div class="alert alert-<%= type %>" role="alert">
    <% if msg.is_a? Array%>
      <%= msg.join("<br/>").html_safe %>
    <% else %>
      <%= msg %>
    <% end %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer pt2 pb2">

  <div class="row mb1">
    <%= link_to "FAQ", faq_path, class:"item" %>
  </div>

  <div class="row">
    <p class="love"><small>Copyright © 2022 Immolib | Fait avec <i class="fas fa-heart"></i></small></p>
  </div>

</footer>

app/views/layouts/_mailer_footer.html.erb
<tr>
  <td class="footer" align='center' valign='bottom'>
    <%= link_to 'immolib', "https://immolib.herokuapp.com" %>
    <p><em>Copyright © 2021</em></p>
  </td>
</tr>

app/views/layouts/_mailer_header.html.erb
<tr>
  <td class="header" align="center" valign="top">
    <h2><%= subtitle || 'Immolib' %></h2>
  </td>
</tr>

app/views/layouts/_navbar.html.erb
<header>
  <nav class='navbar'>
    <%= link_to root_path, class: 'navbar__brand' do %>
      <div class='logo'></div>
      <h1 class='title'>immolib</h1>
    <% end %>
    <div class='navbar__items'>
      <% if current_user && current_user.is_admin? %>
        <%= link_to 'Administration', admin_root_path %>
      <% end %>
      <% if user_signed_in? %>
        <%= link_to 'Mon espace immolib', user_path(current_user), class: 'item item-active' %>
        <%= link_to 'Me déconnecter', destroy_user_session_path, method: :delete, class: 'item' %>
      <% else %>
        <%= link_to 'Enregistrer mon logement', welcome_user_path, class: 'item' %>
        <p class="item connection-btn"> Connexion <i class="fas fa-chevron-down"></i></p>
        <div class="navbar__items__connection__menu">
          <%= link_to 'Se connecter', new_user_session_path, class: 'item primary' %>
          <%= link_to "S'inscrire", new_user_registration_path, class: 'item primary' %>
        </div>
      <% end %>
    </div>
  </nav>
  <div class="hamburger-btn">
    <span class='hamburger-btn__icon'></span>
  </div>
  <nav class='hamburger-menu'>
    <%= link_to root_path, class: 'navbar__brand' do %>
      <p class="text-center mt2"><span class="bolder">Bienvenue</span> ✌️</p>
    <% end %>
    <div class='navbar__items'>
      <% if current_user && current_user.is_admin? %>
        <%= link_to 'Administration', admin_root_path %>
      <% end %>
      <% if user_signed_in? %>
        <%= link_to 'Mon espace immolib', user_path(current_user), class: 'item' %>
        <%= link_to 'Me déconnecter', destroy_user_session_path, method: :delete, class: 'item' %>
      <% else %>
        <%= link_to 'Enregistrer mon logement', welcome_user_path, class: 'item' %>
        <p class="item connection-btn"> Connexion <i class="fas fa-chevron-down"></i></p>
        <div class="navbar__items__connection__menu">
          <%= link_to 'Se connecter', new_user_session_path, class: 'item' %>
          <%= link_to "S'inscrire", new_user_registration_path, class: 'item' %>
        </div>
      <% end %>
    </div>
  </nav>
</header>

<%= javascript_include_tag 'navbar.js' %>

app/views/layouts/_picture_modal.html.erb
<div class="picture-modal-wrapper hidden">
  <div class='blocker'></div>
  <div class='modal'>
    <i class="fas fa-times modal-close primary"></i>
    <%= form_with url: url, local: true, class: "form", id: "item-form", multipart: true do |f| %>
      <div class="field">
        <%= f.file_field type, is: "drop-files", label: "Déposer un fichier au format jpeg ou png", help: "Vous pouvez glisser-déposer votre photo ici", accept: 'image/png,image/gif,image/jpeg' %>
      </div>
      <div class="text-center">
        <%= f.submit "Valider", class: "btn white-btn bg-primary" %>
      </div>
    <%end%>
  </div>
</div>

<%= javascript_include_tag "pic-modal.js" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Immolib</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1">

    <script src="https://kit.fontawesome.com/8e2a5370b3.js" crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <script src="https://cdn.jsdelivr.net/npm/pickadate@5.0.0-alpha.2/builds/index.min.js"></script>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag "activestorage" %>
  </head>

  <body>
    <noscript> <meta HTTP-EQUIV="Refresh" CONTENT="0;URL=/no_js.html"> </noscript>

    <%= render 'layouts/navbar' %>
    <%= render 'layouts/flash' %>

    <main>
      <%= yield %>
    </main>

    <%= render 'layouts/footer' %>

    <script src="https://js.stripe.com/v3/"></script>
    <script type="module" src="//unpkg.com/@grafikart/drop-files-element"></script>

  </body>
</html>